#!/usr/bin/env python3
"""
Monster/Object Refresh File Converter for Advent MUD
====================================================

Converts text-format refresh file (monfil.fil) to binary format
expected by the workman system on RSTS/E.

This file controls respawning of monsters and objects in the dungeon.

Format of monfil.fil:
    MON
    <room_number>
    <chance%>
    <monster_name>
    <attack_level>
    <defense_level>
    <hp>
    <damage>
    <special_attacks>  (e.g., /FO75/ for follow, /PA20/ for paralysis)
    <xp>
    <flag1>
    <flag2>
    <flag3>

    OBJ
    <room_number>
    <chance%>
    <object_name>

Written by Claude (an AI), December 2025.
"""

import sys
from pathlib import Path
from dataclasses import dataclass
from typing import Optional


@dataclass
class Monster:
    """Monster spawn definition."""
    room: int
    chance: int
    name: str
    attack_level: int
    defense_level: int
    hp: int
    damage: int
    special: str
    xp: int
    flags: list[int]


@dataclass
class Object:
    """Object spawn definition."""
    room: int
    chance: int
    name: str


def parse_refresh_file(filepath: Path) -> tuple[list[Monster], list[Object]]:
    """Parse the refresh file and return monsters and objects."""
    monsters = []
    objects = []

    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        lines = [line.strip() for line in f.readlines()]

    i = 0
    while i < len(lines):
        line = lines[i]

        if line == 'MON':
            # Parse monster
            try:
                room = int(lines[i+1].strip())
                chance = int(lines[i+2].strip())
                name = lines[i+3].strip()
                attack = int(lines[i+4].strip())
                defense = int(lines[i+5].strip())
                hp = int(lines[i+6].strip())
                damage = int(lines[i+7].strip())
                special = lines[i+8].strip()
                xp = int(lines[i+9].strip())
                flag1 = int(lines[i+10].strip())
                flag2 = int(lines[i+11].strip())
                flag3 = int(lines[i+12].strip())

                monsters.append(Monster(
                    room=room, chance=chance, name=name,
                    attack_level=attack, defense_level=defense,
                    hp=hp, damage=damage, special=special,
                    xp=xp, flags=[flag1, flag2, flag3]
                ))
                i += 13
            except (IndexError, ValueError) as e:
                print(f"Warning: Error parsing monster at line {i}: {e}")
                i += 1

        elif line == 'OBJ':
            # Parse object
            try:
                room = int(lines[i+1].strip())
                chance = int(lines[i+2].strip())
                name = lines[i+3].strip()

                objects.append(Object(room=room, chance=chance, name=name))
                i += 4
            except (IndexError, ValueError) as e:
                print(f"Warning: Error parsing object at line {i}: {e}")
                i += 1
        else:
            i += 1

    return monsters, objects


def write_refresh_ctl(monsters: list[Monster], objects: list[Object], filepath: Path):
    """Write refresh data in RSTS/E REFRSH.CTL format."""
    with open(filepath, 'w') as f:
        f.write("; Advent Refresh Control File\n")
        f.write("; Generated by convert_monsters.py\n")
        f.write(f"; {len(monsters)} monsters, {len(objects)} objects\n")
        f.write(";\n")

        f.write("; MONSTERS\n")
        for m in monsters:
            f.write(f"M,{m.room},{m.chance},{m.name},{m.attack_level},{m.defense_level},")
            f.write(f"{m.hp},{m.damage},{m.special},{m.xp}\n")

        f.write(";\n; OBJECTS\n")
        for o in objects:
            f.write(f"O,{o.room},{o.chance},{o.name}\n")


def print_summary(monsters: list[Monster], objects: list[Object]):
    """Print summary statistics."""
    print(f"\n=== Summary ===")
    print(f"Total monsters: {len(monsters)}")
    print(f"Total objects:  {len(objects)}")

    # Monster stats
    if monsters:
        rooms_with_monsters = len(set(m.room for m in monsters))
        avg_hp = sum(m.hp for m in monsters) / len(monsters)
        print(f"\nMonster rooms:  {rooms_with_monsters}")
        print(f"Average HP:     {avg_hp:.1f}")

        print("\nSample monsters:")
        for m in monsters[:5]:
            print(f"  Room {m.room}: {m.name} (HP:{m.hp}, DMG:{m.damage}, XP:{m.xp})")

    # Object stats
    if objects:
        print("\nSample objects:")
        for o in objects[:5]:
            print(f"  Room {o.room}: {o.name} ({o.chance}% chance)")


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: convert_monsters.py <input.fil> [output.ctl]")
        print()
        print("Converts monfil.fil to REFRSH.CTL format")
        sys.exit(1)

    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else Path('REFRSH.CTL')

    print(f"Reading {input_file}...")
    monsters, objects = parse_refresh_file(input_file)

    print_summary(monsters, objects)

    print(f"\nWriting {output_file}...")
    write_refresh_ctl(monsters, objects, output_file)

    print("Done!")


if __name__ == '__main__':
    main()
